version: '3.9'

services:
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'mysecretpassword'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data
    ports: 
      - '5432:5432'

volumes:
  data: