version: '3.9'

services:
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - data:/var/lib/postgresql/data
    ports: 
      - '5432:5432'

volumes:
  data: